//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoFrame.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ALBUM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_ALBUM()
        {
            this.M_PHOTO = new HashSet<M_PHOTO>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Descript { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_PHOTO> M_PHOTO { get; set; }
    }
}
