//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoFrame.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PHOTO
    {
        public System.Guid Id { get; set; }
        public string FilePath { get; set; }
        public bool IsFavorite { get; set; }
        public Nullable<System.Guid> AlbumId { get; set; }
    
        public virtual M_ALBUM M_ALBUM { get; set; }
    }
}
